# Generated by Django 5.2.7 on 2025-11-22 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ChapitreApp", "0001_initial"),
        ("FormationApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapitre",
            name="formation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapitres",
                to="FormationApp.formation",
            ),
        ),
    ]
