# Generated by Django 6.0 on 2025-12-18 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_quiz', to=settings.AUTH_USER_MODEL),
        ),
    ]
