# Generated by Django 5.2.7 on 2025-11-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_naissance",
            field=models.DateField(blank=True, null=True),
        ),
    ]
